/triton/state_maintainer/component_one:
  ros__parameters:
    pose_offset:
      pos:
        x: 20.0
        y: 0.0
        z: 0.0
      orient:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    use_sim_time: false
