/triton/state_maintainer/component_one:
  ros__parameters:
    pose_offset:
      pos:
        x: 20.0
        y: 0.0
        z: 0.0
      ang:
        r: 0.0
        p: 0.0
        y: 0.0
    use_sim_time: false
