pipeline_manager:
  ros__parameters:
    pipeline:
      components:
        - object_recognition::ObjectRecognizer
      namespace: /triton/object_recognition
      pkg_name: triton_object_recognition
      remap_rules:
        - /triton/object_recognition/object_recognizer/in:=/tr/gazebo_drivers/camera/front/image_raw
    use_sim_time: false
