name: ROS2 Build and Test CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Check out ubc-subbots/triton
        uses: actions/checkout@v2

      - name: Setup ROS2 distro and system deps
        uses: ros-tooling/setup-ros@v0.2
        with: 
          required-ros-distributions: foxy

      - name: Install deps with rosdep
        run: |
          rosdep update
          rosdep install -i --from-path src --rosdistro foxy -y

      - name: Install OpenCV 4.5.3
        uses: Dovyski/setup-opencv-action@v1
        with:
          opencv-version: 4.5.3
          CMAKE_BUILD_TYPE: RELEASE          

      - name: Source setup and build then test using colcon
        run: |
          source /opt/ros/foxy/setup.bash
          source /usr/share/gazebo/setup.sh
          colcon build
          source ./install/setup.bash
          colcon test
          colcon test-result --verbose



