name: ROS2 Build and Test CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:

      - name: Check out ubc-subbots/triton
        uses: actions/checkout@v2

      - name: Setup ROS2 distro and system deps
        uses: ros-tooling/setup-ros@v0.2
        with: 
          required-ros-distributions: foxy

      - name: Install deps with rosdep
        run: |
          rosdep update
          rosdep install -i --from-path src --rosdistro foxy -y
          
      - name: Cache OpenCV
        id: opencv-cache
        uses: actions/cache@v2
        with:
          path: ./opencv-install
          key: ${{ runner.os }}-opencv-cache

      - name: Install OpenCV
        uses: rayandrews/with-opencv-action@v1
        with:  
          dir: ./opencv-install
          cached: ${{ steps.opencv-cache.outputs.cache-hit }}
          opencv-version: '4.5.3'
          CMAKE_BUILD_TYPE: RELEASE   
          ENABLE_PRECOMPILED_HEADERS: OFF
          
      - name: Ignore with colcon build
        run: |
          touch ./opencv-install/COLCON_IGNORE
          
      - name: Source setup and build then test using colcon
        env:
          LD_LIBRARY_PATH: /usr/local/lib/
        run: |
          source /opt/ros/foxy/setup.bash
          source /usr/share/gazebo/setup.sh
          colcon build --cmake-args -DCMAKE_CXX_STANDARD=14
          source ./install/setup.bash
          colcon test
          colcon test-result --verbose



