name: ROS2 Build and Test CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Check out ubc-subbots/triton
        uses: actions/checkout@v2

      - name: Setup ROS2 distro and system deps
        uses: ros-tooling/setup-ros@0.0.26
        with: 
          required-ros-distributions: foxy

      - name: Install deps with rosdep
        run: |
          rosdep update
          rosdep install -i --from-path src --rosdistro foxy -y

      - name: Source setup and build then test using colcon
        run: |
          source /opt/ros/foxy/setup.bash
          source /usr/share/gazebo/setup.sh
          colcon build
          source ./install/setup.bash
          launch_test src/triton_pipeline/test/test_pipeline_run_comp_not_exist.py 
          colcon test
          colcon test-result --verbose



